from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from datetime import datetime

def fill_pdf_form(data):
    """
    Generate filled PDF form with dynamic questions and answers
    """
    file_path = "filled_form.pdf"
    c = canvas.Canvas(file_path, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawString(1*inch, height - 1*inch, "Filled Government Form")
    
    # Horizontal line
    c.line(1*inch, height - 1.2*inch, width - 1*inch, height - 1.2*inch)
    
    # Form fields - dynamic
    c.setFont("Helvetica", 12)
    y_position = height - 2*inch
    
    # Get answers dict
    answers = data.get('answers', {})
    
    # Display all question-answer pairs
    for q_id, answer_data in answers.items():
        if y_position < 2*inch:
            # Create new page if needed
            c.showPage()
            y_position = height - 1*inch
        
        question = answer_data.get('question', '')
        answer = answer_data.get('answer', '')
        
        c.setFont("Helvetica-Bold", 11)
        # Wrap question text
        question_lines = wrap_text(c, question, width - 2*inch, "Helvetica-Bold", 11)
        for line in question_lines:
            c.drawString(1*inch, y_position, line)
            y_position -= 0.3*inch
        
        c.setFont("Helvetica", 11)
        # Wrap answer text
        answer_lines = wrap_text(c, str(answer), width - 2*inch, "Helvetica", 11)
        for line in answer_lines:
            c.drawString(1.2*inch, y_position, line)
            y_position -= 0.3*inch
        
        y_position -= 0.2*inch  # Extra space between questions
    
    # Attached documents section
    documents = data.get('documents', {})
    if documents:
        y_position -= 0.5*inch
        c.setFont("Helvetica-Bold", 12)
        c.drawString(1*inch, y_position, "Attached Documents:")
        y_position -= 0.4*inch
        
        for doc_type, doc_info in documents.items():
            c.setFont("Helvetica", 11)
            c.drawString(1.2*inch, y_position, f"• {doc_type}: {doc_info.get('filename', 'N/A')}")
            y_position -= 0.3*inch
            
            # Show extracted text if available
            if doc_info.get('extracted_text'):
                c.setFont("Helvetica-Oblique", 9)
                text_preview = doc_info['extracted_text'][:200] + "..."
                preview_lines = wrap_text(c, text_preview, width - 2.5*inch, "Helvetica-Oblique", 9)
                for line in preview_lines[:3]:  # Max 3 lines
                    c.drawString(1.5*inch, y_position, line)
                    y_position -= 0.25*inch
                y_position -= 0.2*inch
    
    # User profile section
    user_profile = data.get('user_profile', {})
    if user_profile:
        y_position -= 0.5*inch
        if y_position < 2*inch:
            c.showPage()
            y_position = height - 1*inch
        
        c.setFont("Helvetica-Bold", 12)
        c.drawString(1*inch, y_position, "User Profile:")
        y_position -= 0.4*inch
        
        c.setFont("Helvetica", 10)
        profile_fields = [
            ("Name", user_profile.get('name')),
            ("Email", user_profile.get('email')),
            ("Phone", user_profile.get('phone')),
        ]
        
        for label, value in profile_fields:
            if value:
                c.drawString(1.2*inch, y_position, f"{label}: {value}")
                y_position -= 0.3*inch
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(1*inch, 1*inch, f"Generated by BharatVoice AI on {datetime.now().strftime('%d-%m-%Y %H:%M')}")
    c.drawString(1*inch, 0.7*inch, "This is an AI-assisted form. Please verify all information.")
    
    c.save()
    return file_path


def wrap_text(canvas_obj, text, max_width, font_name, font_size):
    """
    Wrap text to fit within max_width
    Returns list of lines
    """
    words = text.split()
    lines = []
    current_line = ""
    
    for word in words:
        test_line = current_line + " " + word if current_line else word
        if canvas_obj.stringWidth(test_line, font_name, font_size) < max_width:
            current_line = test_line
        else:
            if current_line:
                lines.append(current_line)
            current_line = word
    
    if current_line:
        lines.append(current_line)
    
    return lines


def generate_pdf(data):
    """
    Legacy function for backward compatibility
    """
    return fill_pdf_form(data)

